"""add notification preferences to user

Revision ID: 09dd4e8ef5c3
Revises: 69ba50fc8bca
Create Date: 2026-08-26 00:39:41.766997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09dd4e8ef5c3'
down_revision = '69ba50fc8bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_bills_due', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('notify_notes_due', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notify_notes_due')
        batch_op.drop_column('notify_bills_due')

    # ### end Alembic commands ###
