"""add changelog_seen_at to user

Revision ID: 0c9e4ccff395
Revises: 271cbb3f0794
Create Date: 2026-08-29 03:35:25.260144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9e4ccff395'
down_revision = '271cbb3f0794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changelog_seen_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('changelog_seen_at')

    # ### end Alembic commands ###
