"""Add archived flag to note

Revision ID: 148a4a347474
Revises: bf40ed834ac6
Create Date: 2026-08-14 21:35:41.527999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148a4a347474'
down_revision = 'bf40ed834ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
