"""add category and import_source to transaction

Revision ID: 1f682cc00dbb
Revises: 8fbf553abfcb
Create Date: 2026-08-23 21:21:14.584667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f682cc00dbb'
down_revision = '8fbf553abfcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('import_source', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('import_source')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
