"""add reminder_hour and calendar_feed_token to user, currency and usd_value to transaction

Revision ID: 261d0d1f8439
Revises: 0c9e4ccff395
Create Date: 2026-09-02 19:26:23.981167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261d0d1f8439'
down_revision = '0c9e4ccff395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('usd_value', sa.Numeric(precision=14, scale=6), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_hour', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calendar_feed_token', sa.String(length=43), nullable=True))
        batch_op.create_unique_constraint('uq_user_calendar_feed_token', ['calendar_feed_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_calendar_feed_token', type_='unique')
        batch_op.drop_column('calendar_feed_token')
        batch_op.drop_column('reminder_hour')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('usd_value')
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
