"""add account deletion and 2FA fields

Revision ID: 271cbb3f0794
Revises: 27de6ed19985
Create Date: 2026-08-27 16:30:24.156822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271cbb3f0794'
down_revision = '27de6ed19985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_code_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('otp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('otp_enabled', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_enabled')
        batch_op.drop_column('otp_secret')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('recovery_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_code_user_id'))

    op.drop_table('recovery_code')
    # ### end Alembic commands ###
