"""add timezone to user

Revision ID: 289148184189
Revises: 5b070c2b8822
Create Date: 2026-08-26 18:08:08.934329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289148184189'
down_revision = '5b070c2b8822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
