"""add recurrence to event

Revision ID: 37707f269ed9
Revises: 4b26ad616162
Create Date: 2026-08-21 00:51:15.641681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37707f269ed9'
down_revision = '4b26ad616162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('recurrence_parent_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_event_recurrence_parent_id'), ['recurrence_parent_id'], unique=False)
        batch_op.create_foreign_key('fk_event_recurrence_parent_id_event', 'event', ['recurrence_parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_recurrence_parent_id_event', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_event_recurrence_parent_id'))
        batch_op.drop_column('recurrence_parent_id')
        batch_op.drop_column('recurrence')

    # ### end Alembic commands ###
