"""Add merchant_category_rule table

Revision ID: 399600bb3726
Revises: 3e05d8548a11
Create Date: 2026-09-22 21:16:20.475378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399600bb3726'
down_revision = '3e05d8548a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The autogenerated diff also included dropping/recreating
    # user.calendar_feed_token's unique constraint as an index-vs-
    # constraint reflection quirk (SQLite reports it differently than
    # how it was originally created) -- unrelated to this migration,
    # not a real schema change, and deliberately left out.
    op.create_table('merchant_category_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('merchant_key', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'merchant_key', name='uq_merchant_category_rule_user_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merchant_category_rule')
    # ### end Alembic commands ###
