"""add source column to exchange_rate

Revision ID: 3b9774294a03
Revises: cadec6fb7b4d
Create Date: 2026-07-31 22:20:12.397177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9774294a03'
down_revision = 'cadec6fb7b4d'
branch_labels = None
depends_on = None


def upgrade():
    # server_default tags any pre-existing row as 'frankfurter' (the prior
    # provider), so the app's own SOURCE-mismatch check in
    # exchange_rate_service.py treats it as stale and refetches from the
    # new provider on the next request, rather than serving old cached
    # data under the new code for up to a full freshness window.
    # Two separate batch blocks: SQLite's batch mode recreates the table
    # once per block, so add-with-default and drop-default have to be
    # separate passes for the backfill to actually apply before the
    # default is removed (combined into one block, SQLite's table rebuild
    # only sees the final no-default state and the backfill never happens).
    with op.batch_alter_table('exchange_rate', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('source', sa.String(length=32), nullable=False, server_default='frankfurter')
        )
    with op.batch_alter_table('exchange_rate', schema=None) as batch_op:
        batch_op.alter_column('source', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_rate', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
