"""Add recurrence interval and end date to transaction

Revision ID: 3e05d8548a11
Revises: e4e4971d3156
Create Date: 2026-09-15 22:47:40.021605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e05d8548a11'
down_revision = 'e4e4971d3156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_interval', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('recurring_end_date', sa.Date(), nullable=True))

    # The drop_index/create_unique_constraint pair Alembic also generated
    # here for user.calendar_feed_token is a spurious artifact of this
    # local dev DB's own history (a unique INDEX from an old manual patch
    # standing in for what should be a unique CONSTRAINT), not a real
    # schema change -- verified against a genuinely fresh DB and omitted,
    # same as the prior migrations that hit this identical artifact.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('recurring_end_date')
        batch_op.drop_column('recurrence_interval')

    # ### end Alembic commands ###
