"""add pinned, color, tag, due_date to notes

Revision ID: 40e3819f7169
Revises: 496646237e1d
Create Date: 2026-07-30 03:56:43.472355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e3819f7169'
down_revision = '496646237e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pinned', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tag', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('due_date')
        batch_op.drop_column('tag')
        batch_op.drop_column('color')
        batch_op.drop_column('pinned')

    # ### end Alembic commands ###
