"""Add recurring_month uniqueness guard to Transaction

Revision ID: 4b26ad616162
Revises: dc49c0b64cbf
Create Date: 2026-08-15 12:56:43.976579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b26ad616162'
down_revision = 'dc49c0b64cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_month', sa.Date(), nullable=True))
        batch_op.create_unique_constraint('uq_transaction_recurring_month', ['user_id', 'description', 'type', 'recurring_month'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('uq_transaction_recurring_month', type_='unique')
        batch_op.drop_column('recurring_month')

    # ### end Alembic commands ###
