"""add notify_events_due to user

Revision ID: 5b070c2b8822
Revises: 0bfc099af955
Create Date: 2026-08-26 02:07:57.257069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b070c2b8822'
down_revision = '0bfc099af955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_events_due', sa.Boolean(), server_default=sa.true(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notify_events_due')

    # ### end Alembic commands ###
