"""add category_budget table

Revision ID: 69ba50fc8bca
Revises: 1f682cc00dbb
Create Date: 2026-08-26 00:04:48.644543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ba50fc8bca'
down_revision = '1f682cc00dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('monthly_cap', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', name='uq_category_budget_user_category')
    )
    with op.batch_alter_table('category_budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_budget_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_budget_user_id'))

    op.drop_table('category_budget')
    # ### end Alembic commands ###
