"""Add account and net_worth_snapshot tables

Revision ID: 8cca5a959964
Revises: 399600bb3726
Create Date: 2026-09-22 22:48:17.030606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cca5a959964'
down_revision = '399600bb3726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The autogenerated diff also included dropping/recreating
    # user.calendar_feed_token's unique constraint as an index-vs-
    # constraint reflection quirk (SQLite reports it differently than how
    # it was originally created) -- unrelated to this migration, not a
    # real schema change, and deliberately left out, same as
    # 399600bb3726 before it.
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_user_id'), ['user_id'], unique=False)

    op.create_table('net_worth_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_assets_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_liabilities_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'snapshot_date', name='uq_net_worth_snapshot_user_date')
    )
    with op.batch_alter_table('net_worth_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_net_worth_snapshot_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('net_worth_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_net_worth_snapshot_user_id'))

    op.drop_table('net_worth_snapshot')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_user_id'))

    op.drop_table('account')
    # ### end Alembic commands ###
