"""add event exception table

Revision ID: 8fbf553abfcb
Revises: 37707f269ed9
Create Date: 2026-08-21 18:32:02.644517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fbf553abfcb'
down_revision = '37707f269ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_exception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anchor_id', sa.Integer(), nullable=False),
    sa.Column('occurrence_start', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['anchor_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anchor_id', 'occurrence_start', name='uq_event_exception_anchor_start')
    )
    with op.batch_alter_table('event_exception', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_exception_anchor_id'), ['anchor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_exception', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_exception_anchor_id'))

    op.drop_table('event_exception')
    # ### end Alembic commands ###
