"""Add deleted_at (trash) to note

Revision ID: dc49c0b64cbf
Revises: 148a4a347474
Create Date: 2026-08-15 00:20:55.137983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc49c0b64cbf'
down_revision = '148a4a347474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_note_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_deleted_at'))
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
