"""Add budget overage alert tracking

Revision ID: e4e4971d3156
Revises: 3d0088f2bf8c
Create Date: 2026-09-15 18:04:37.420542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e4971d3156'
down_revision = '3d0088f2bf8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alerted_month', sa.Date(), nullable=True))

    with op.batch_alter_table('category_budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alerted_month', sa.Date(), nullable=True))

    # sa.true(), not sa.text('1') -- the text() form works against local
    # SQLite but breaks Postgres (psycopg2.errors.DatatypeMismatch); see
    # CLAUDE.md's "Any new db.Boolean column migration" convention.
    #
    # The drop_index/create_unique_constraint pair Alembic also generated
    # here for user.calendar_feed_token is a spurious artifact of this
    # local dev DB's own history (a unique INDEX from an old manual patch
    # standing in for what should be a unique CONSTRAINT), not a real
    # schema change -- verified against a genuinely fresh DB and omitted,
    # same as the two prior migrations that hit this identical artifact.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_budget_alerts', sa.Boolean(), server_default=sa.true(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notify_budget_alerts')

    with op.batch_alter_table('category_budget', schema=None) as batch_op:
        batch_op.drop_column('alerted_month')

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_column('alerted_month')

    # ### end Alembic commands ###
